### ISSUE TITLE
Finalize colors/dark + light mode

### ISSUE THREAD

**Issue by ezrichards** [ColoradoSchoolOfMines/coloradoschoolofmines.github.io#1]
Figure out the color scheme for the site. This should include "ACM blue" which is `#0083c5`. It doesn't have to be anything too serious, we could just do basic white and ACM blue.

Also, it would be cool if we could have light and dark modes (or toggle by system preference).
See: https://dev.to/whitep4nth3r/light-and-dark-mode-in-just-14-lines-of-css-424e

**Comment by sinkkkk** [comment]
hello! can you assign this issue to me? would be happy to help out.

**Comment by ezrichards** [comment]
@alongoria @sinkkkk Hi everyone, I appreciate the interest. I'd like to meet with contributors before they start working as this is intended to be a beginner project. Please add me on Discord at Ethan#2957 and we can discuss further.

**Comment by ezrichards** [comment]
Accessibility (end of project type thing): https://wave.webaim.org/ @Idwill151
